version: '3'

services:
  vless:
    image: teddysun/xray
    container_name: vless-server
    restart: always
    environment:
      - TZ=UTC
    volumes:
      - ./config:/etc/xray
      - ./logs:/var/log/xray
    networks:
      - traefik_web-network
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.tcp_congestion_control=bbr
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_web-network"
      # TCP Router для Reality (passthrough mode)
      - "traefik.tcp.routers.vless-reality.rule=HostSNI(`v-server.perek.rest`)"
      - "traefik.tcp.routers.vless-reality.entrypoints=websecure"
      - "traefik.tcp.routers.vless-reality.service=vless-reality-service"
      - "traefik.tcp.routers.vless-reality.tls.passthrough=true"
      - "traefik.tcp.services.vless-reality-service.loadbalancer.server.port=443"

networks:
  traefik_web-network:
    external: true