version: '3'

services:
  vless:
    image: teddysun/xray
    container_name: vless-server
    restart: always
    environment:
      - TZ=UTC
    volumes:
      - ./config:/etc/xray
      - ./logs:/var/log/xray
    networks:
      - traefik_web-network
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.vless-tcp.rule=HostSNI(`vless-server.perek.rest`)"
      - "traefik.tcp.routers.vless-tcp.entrypoints=vless"
      - "traefik.tcp.routers.vless-tcp.tls=true"
      - "traefik.tcp.routers.vless-tcp.tls.certresolver=myresolver"
      - "traefik.tcp.routers.vless-tcp.service=vless-tcp-service"
      - "traefik.tcp.services.vless-tcp-service.loadbalancer.server.port=8443"

networks:
  traefik_web-network:
    external: true