version: '3'

services:
  vless:
    image: teddysun/xray
    container_name: vless-server
    restart: always
    environment:
      - TZ=UTC
    volumes:
      - ./config:/etc/xray
      - ./logs:/var/log/xray
    expose:
      - "8443"
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.tcp_congestion_control=bbr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vless.rule=Host(`krasno.bond`)"
      - "traefik.http.routers.vless.entrypoints=websecure"
      - "traefik.http.routers.vless.tls=true"
      - "traefik.http.routers.vless.tls.certresolver=myresolver"
      - "traefik.http.services.vless.loadbalancer.server.port=8443"
    networks:
      - traefik_web-network

networks:
  traefik_web-network:
    external: true