version: '3'

services:
  vless:
    image: teddysun/xray
    container_name: vless-server
    restart: always
    environment:
      - TZ=UTC
    volumes:
      - ./config:/etc/xray
      - ./logs:/var/log/xray
    networks:
      - traefik_web-network
    labels:
      - "traefik.enable=true"
      # HTTPS роутер для WebSocket
      - "traefik.http.routers.vless-https.rule=Host(`krasno.bond`)"
      - "traefik.http.routers.vless-https.entrypoints=websecure"
      - "traefik.http.routers.vless-https.tls=true"
      - "traefik.http.routers.vless-https.tls.certresolver=myresolver"
      - "traefik.http.routers.vless-https.service=vless-service"
      - "traefik.http.services.vless-service.loadbalancer.server.port=8443"
      # HTTP редирект на HTTPS
      - "traefik.http.routers.vless-http.rule=Host(`krasno.bond`)"
      - "traefik.http.routers.vless-http.entrypoints=web"
      - "traefik.http.routers.vless-http.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"

networks:
  traefik_web-network:
    external: true